### PR TITLE
New Plugin OTP

### PR DESCRIPTION
**Pull request by BugBountyzip**
Dear team, 

I have added a new Plugin to help user generate OTP.

Thank you

### CODE REVIEW

**Comment by Corb3nik** [comment]
Thanks for the plugin submission @BugBountyzip!

Plugin code should usually be hosted in a repository under your Github account (like https://github.com/caido-community/authmatrix), not in this documentation repository.

You would then submit a PR to https://github.com/caido/store to have it available in the store for everyone to use.

Would you like us to transfer your code into a https://github.com/caido-community/otp-generator repository?

Alternatively, you could use this [starterkit template](https://github.com/caido/starterkit-plugin) and move the code there yourself.

**Comment by BugBountyzip** [comment]
Thank you for your response. Please allow me some time to move it to the correct path.

**Comment by Sytten** [comment]
@BugBountyzip Hey! I improved the documentation of the guide: https://developer.caido.io/guides/distribution/store.html
It should be clearer

**Comment by BugBountyzip** [comment]
Hello @Sytten ,

I have moved it.

https://github.com/BugBountyzip/otp-generator

**Comment by Sytten** [comment]
I see you forked authmatrix, I would suggest removing the code you dont need or starting from the simpler starterkit-plugin to make it more maintainable

**Comment by BugBountyzip** [comment]
Almost done

https://github.com/BugBountyzip/OtpGenerator/releases

**Pull request closed without merging**
